<?php

/**
 * @file
 * Install functions for Persistent Update API module.
 */

/**
 * Implements hook_install().
 */
function persistent_update_install() {
  // Set the schema back before the current Persistent Updates update hook.
  drupal_set_installed_schema_version('persistent_update', 8000);
}

/**
 * PERSISTENT: Trigger all Persistent Updates.
 */
function persistent_update_update_8001() {
  // Empty update hook placeholder.
}
